storage: ./storage
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@videobrew/*':
    access: $all
    publish: $all
    # commented so npmjs registry is not used
    # proxy:
  '**':
    access: $all
    publish: $all
    proxy: npmjs