name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npx lerna bootstrap
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build all packages
        run: npx lerna run build
      - name: Test all packages
        run: npm run ci:test
  upload-coveralls:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: [
          { base-path: ./scripts, flag-name: scripts },
          { base-path: ./packages/client, flag-name: client },
          { base-path: ./packages/cli, flag-name: cli },
          { base-path: ./packages/editor, flag-name: editor },
        ]
    steps:
      - uses: coverallsapp/github-action@v2
        with:
          base-path: ${{ matrix.packages.base-path }}
          flag-name: ${{ matrix.packages.flag-name }}
          parallel: true
  finish:
    needs: upload-coveralls
    if: "!cancelled()"
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true