name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - run: npx lerna bootstrap
      - run: npx lerna run ci:test
      - name: Coveralls for @videobrew/client
        uses: coverallsapp/github-action@v2.0.0
        with:
          base-path: ./packages/client
          flag_name: client
      - name: Coveralls for @videobrew/cli
        uses: coverallsapp/github-action@v2.0.0
        with:
          base-path: ./packages/cli
          flag_name: cli
      - name: Coveralls for @videobrew/editor
        uses: coverallsapp/github-action@v2.0.0
        with:
          base-path: ./packages/editor
          flag_name: editor
